//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class semantıcEntities : DbContext
{
    public semantıcEntities()
        : base("name=semantıcEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<admın> admın { get; set; }
    public DbSet<Classification> Classification { get; set; }
    public DbSet<CLUSTER> CLUSTER { get; set; }
    public DbSet<DATASET> DATASET { get; set; }
    public DbSet<DOCUMENT> DOCUMENT { get; set; }
    public DbSet<FILE> FILE { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<USER> USER { get; set; }
}
