//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DENEMEEntities : DbContext
{
    public DENEMEEntities()
        : base("name=DENEMEEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ADMIN> ADMIN { get; set; }
    public virtual DbSet<CLUSTER> CLUSTER { get; set; }
    public virtual DbSet<DATASET> DATASET { get; set; }
    public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<USER> USER { get; set; }
}
